name: Get Google Sheets
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Python Dependencies
      run: pip install -r actions/requirements.txt
    - name: Get Google Sheets
      run: python actions/get_google_sheets.py
      env:
        SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        SPREADSHEET_ID: ${{ secrets.DEVICE_TESTING_A1_SPREADSHEET_ID }}
    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "actions-user"
        git add data/device-testing/
        git commit -m "GH ACTION Headlines $(date)" || echo "No changes to commit."
        git push origin main || echo "No changes to push."
